backend:
  name: github
  repo: ipp-editorial/my-news-website
  branch: main

local_backend: true

media_folder: "src/public/images/gallery"
public_folder: "/images/gallery"

collections:
  - name: "news"
    label: "اخبار"
    folder: "src/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{fields.custom_slug}}"
    fields:
    - { name: "tags", widget: "hidden", default: "news" }
      - { label: "عنوان", name: "title", widget: "string" }
      - { label: "تاریخ", name: "date", widget: "datetime" }
      - label: "برچسب‌ها"
        name: "tags"
        widget: "select"
        multiple: true
        options: ["اخبار", "بیانیه‌ها", "زندانیان سیاسی", "شهادت‌ها"]
        required: false
      - { label: "اسلاگ", name: "custom_slug", widget: "string", required: false }
      - { label: "تصویر", name: "image", widget: "image", required: false }
      - { label: "متن اصلی", name: "body", widget: "markdown" }
